export enum Status {
  REQUEST_REJECTED = "REQUEST_REJECTED",
  RESPONSE_REJECTED = "RESPONSE_REJECTED",
  NETWORK_ERROR = "NETWORK_ERROR",
  TIMEOUT_ERROR = "TIMEOUT_ERROR",
  CANCELLED_ERROR = "CANCELLED_ERROR",
  INVALID_REQUEST_ERROR = "INVALID_REQUEST_ERROR",
  INVALID_RESPONSE_ERROR = "INVALID_RESPONSE_ERROR",
  CODE_ERROR = "CODE_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
}
